# Generated by Django 3.2.4 on 2021-06-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='entry',
            new_name='topic',
        ),
    ]
